In [2]:
# Importar librerías
import numpy as np

# Función de activación Sigmoide
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivada de la sigmoide
def sigmoid_deriv(x):
    return x * (1 - x)

# Datos de entrenamiento (XOR)
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Inicializar pesos aleatorios
np.random.seed(1)

pesos_entrada_oculta = np.random.uniform(size=(2,4))
bias_oculta = np.random.uniform(size=(1,4))

pesos_oculta_salida = np.random.uniform(size=(4,1))
bias_salida = np.random.uniform(size=(1,1))

# Tasa de aprendizaje
lr = 0.5

# Entrenamiento
for epoch in range(10000):

    # Forward propagation
    capa_oculta = sigmoid(np.dot(X, pesos_entrada_oculta) + bias_oculta)
    salida = sigmoid(np.dot(capa_oculta, pesos_oculta_salida) + bias_salida)

    # Error
    error = y - salida

    # Backpropagation
    d_salida = error * sigmoid_deriv(salida)
    
    error_oculta = d_salida.dot(pesos_oculta_salida.T)
    d_oculta = error_oculta * sigmoid_deriv(capa_oculta)

    # Actualizar pesos y bias
    pesos_oculta_salida += capa_oculta.T.dot(d_salida) * lr
    bias_salida += np.sum(d_salida, axis=0, keepdims=True) * lr

    pesos_entrada_oculta += X.T.dot(d_oculta) * lr
    bias_oculta += np.sum(d_oculta, axis=0, keepdims=True) * lr

    # Mostrar error cada 1000 iteraciones
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch} - Loss: {loss}")

# Resultados finales
print("\nResultados finales:")
print("Entrada:")
print(X)

print("\nSalida esperada:")
print(y)

print("\nSalida predicha por la red:")
print(salida)

Epoch 0 - Loss: 0.3673710629757361
Epoch 1000 - Loss: 0.05763654632877206
Epoch 2000 - Loss: 0.00543629512873222
Epoch 3000 - Loss: 0.0017823395948854067
Epoch 4000 - Loss: 0.0009653606198862437
Epoch 5000 - Loss: 0.0006422089544530253
Epoch 6000 - Loss: 0.00047490086374296474
Epoch 7000 - Loss: 0.00037417709684767344
Epoch 8000 - Loss: 0.00030745137264935444
Epoch 9000 - Loss: 0.00026023935695245555

Resultados finales:
Entrada:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Salida esperada:
[[0]
 [1]
 [1]
 [0]]

Salida predicha por la red:
[[0.01228616]
 [0.98807247]
 [0.98231021]
 [0.01716815]]


Se muestra la disminución ded la perdida durante el entrenamiento, tambien podemos ver la tabla de resultados finales en la salida esperada y la salida predicha por la red.

también calculamos la salida de una red neuronal, el error en la funcion de perdida, calculamos el algoritmo de retropropagación actualizacion de pesos y sesgos y por ultimo la mejora del modelo a medida de que disminuye el error